name: flutter_api_services
description: Templates and helper classes for Flutter HTTP/API services.
version: 0.1.1
homepage: https://github.com/dan1229/flutter_api_services.git

environment:
  sdk: ">=3.2.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
