name: Analyze

on:
  push

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          cache: true
          cache-key: flutter1 # optional, change this to force refresh cache

      - name: Flutter analyze
        run: flutter analyze --fatal-infos
