name: Test

on:
  push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          cache: true
          cache-key: flutter1 # optional, change this to force refresh cache

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --coverage

      - name: Upload to CodeCov
        uses: codecov/codecov-action@v1.2.1
        with:
          file: coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
